title: MICS Conference Deadlines
description: Countdowns to medical imaging, computer vision, and machine learning conference deadlines
author: Leo Fillioux

domain: "https://mics-lab.github.io/deadlines"
baseurl: "deadlines"

github_username: MICS-Lab
github_repo: deadlines

markdown: kramdown

include: ['_pages']
