title: MICS Conference Deadlines
description: Countdowns to top medical imaging, CV, ML conference deadlines.
author: Leo Fillioux

domain: "https://mics-lab.github.io/deadlines"
baseurl: "/deadlines"

github_username: leofillioux
github_repo: mics-lab.github.io

markdown: kramdown

include: ['_pages']
